version: '3.8'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    image: migratio_map_nginx_new
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: migratio_map_frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: migratio_map_backend
    expose:
      - "8000"
    environment:
      - ENV_FILE=.env
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - NEO4J_AUTH_ENABLED=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_AUTH=neo4j/test
    depends_on:
      - neo4j
      - kafka
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src

  flink-job:
    build:
      context: ./flink
    image: migratio_map_flink-job
    depends_on:
      - flink
      - kafka
      - neo4j
    restart: unless-stopped

  flink:
    image: flink:1.15.0-scala_2.12
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink
    ports:
      - "8081:8081"
    restart: unless-stopped

  flink-taskmanager:
    image: flink:1.15.0-scala_2.12
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink
    depends_on:
      - flink
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  neo4j:
    image: neo4j:4.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,gds.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*,gds.*
      NEO4J_dbms_security_auth__enabled: "true"
      NEO4J_AUTH: neo4j/test
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  neo4j_data:
